# Generated by Django 3.1.1 on 2020-10-07 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('argorithms', '0004_auto_20201004_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='argorithm',
            name='like_users',
            field=models.ManyToManyField(related_name='like_argorithms', to=settings.AUTH_USER_MODEL),
        ),
    ]
